### ISSUE TITLE
Error al acualizar

### ISSUE THREAD

**Issue by pribaqnet** [dondominio/whmcs#15]
`Se ha producido un error:
Error while copying /tmp/jKTDX8/dondominio-whmcs-024da7c/src/includes/dondominio into /var/www/vhosts/nuvol.cat/clients.nuvol.cat/includes/dondominio_61d9aed53ff0a1: rename(/tmp/jKTDX8/dondominio-whmcs-024da7c/src/includes/dondominio,/var/www/vhosts/nuvol.cat/clients.nuvol.cat/includes/dondominio_61d9aed53ff0a1): No such file or directory`

**Comment by JAndreuSoler** [comment]
Hola, podrías decirme desde que versión del módulo de DonDominio estas intentando actualizar?

**Comment by pribaqnet** [comment]
Versión WHMCS | 8.3.2-release.1
Versión módulo | 2.1.4

**Comment by JAndreuSoler** [comment]
Has comprobado que tengas permisos de lectura y escritura tanto en el directorio temporal como en la carpeta `var/www/vhosts/nuvol.cat/clients.nuvol.cat/includes` ?

**Comment by pribaqnet** [comment]
Si. En todo caso, aunque estaría bien encontrar el error, ¿puedo actualizar subiendo los archivos no?

**Comment by JAndreuSoler** [comment]
Sí, puedes volver a realizar una Instalación sencilla copiando las carpetas `src/modules` y `src/includes` dentro de la carpeta raíz de WHMCS.
