### ISSUE TITLE
No se visualizan enlaces en la parte derecha y no se puede editar la config

### ISSUE THREAD

**Issue by alvaropeso97** [dondominio/whmcs#32]
Tras haber actualizado de la versión 2.1.2  a la 2.2.18 no puedo editar nada de la configuración, aunque acceda a cualquiera de los enlaces de la página de inicio del módulo, ahí se queda.

Tampoco puedo ver lo dominios disponibles en mi cuenta de dondominio para transferirlos y tampoco ver los productos SSL disponibles para crear el producto SSL en WHMCS.

![image](https://github.com/dondominio/whmcs/assets/23009799/bb19d852-2a66-4050-971c-a4ba616d5fb4)

![image](https://github.com/dondominio/whmcs/assets/23009799/ee3ee343-ae89-4199-9115-a1c26eeb7d3c)

Versión de WHMCS 8.8.0
Versión de PHP 8.1 con todos los requerimientos y extenisiones habilitadas

**Comment by JAndreuSoler** [comment]
Hola, parece que ha habido un error durante la actualización, ya que el menú que te aparece es el de la versión 2.1 y no de la 2.2,  puedes volver a realizar una instalación sencilla copiando las carpetas `src/modules` y `src/includes` dentro de la carpeta raíz de WHMCS y todo debería funcionar correctamente.

**Comment by alvaropeso97** [comment]
Buenas,

Lo he hecho varias veces y con diferentes versiones para comprobarlo y
sigue pasando lo mismo.

También he probado a borrar todo lo relativo a Dondominio y volverlo a
instalar.

**Comment by JAndreuSoler** [comment]
¿Al eliminar las carpetas `src/modules/addons/dondominio`, `src/modules/registrars/dondominio` y `src/includes/dondominio`, y volver a realizar la instalación, te aparece el mismo menú de las imágenes o te aparece uno distinto?

**Comment by alvaropeso97** [comment]
El mismo, exactamente he borrado todas las carpetas del modulo.

**Comment by JAndreuSoler** [comment]
Parece que se trata de un problema de cache de WHMCS, puedes intenta limpiar la cache de plantillas.

**Comment by JAndreuSoler** [comment]
Parece que se trata de un problema de cache de WHMCS, puedes intenta limpiar la cache de plantillas en ` Utilities > System > System Cleanup > Empty Template Cache`.

**Comment by JAndreuSoler** [comment]
Parece que se trata de un problema de cache de WHMCS, puedes intentar limpiar la cache de plantillas en `Utilities > System > System Cleanup > Empty Template Cache`, comprueba que se elimina la cache de `admin/templates_c`, si no puedes borrarla a mano.

https://docs.whmcs.com/System_Cleanup
